### ISSUE TITLE
reconnect local video problems

### ISSUE THREAD

**Issue by hei-yu-fa** [havfo/multiparty-meeting#104]
when the network broken and connected later, the local video element is black.
so I added the codes.
       
[RoomClient.js.zip](https://github.com/havfo/multiparty-meeting/files/3737475/RoomClient.js.zip)

**Comment by misi** [comment]
@hei-yu-fa on which commit version of roomclient did you modified in attached file. Please send a Pull Request instead of such  file attachment to make for us more easy to check your suggested changes.

If you don't mind I will close this issue for now, and I ask you to open based on actual branches a new Pull Request with your suggested changes. 

Many thanks for your patience and cooperation!
