### ISSUE TITLE
Landing page for unsupported browsers

### ISSUE THREAD

**Issue by havfo** [havfo/multiparty-meeting#108]
Create a landing page for unsupported browsers

**Comment by misi** [comment]
We need to test it on iOS and Chrome see #120

**Comment by misi** [comment]
Chromium added, because of Linux Mint.

**Comment by La-Fleur** [comment]
Hi All, still having trouble on not-so-old iOS devices

iPad mini 2 -iOS 12.4.9 (latest Nov-2020)
iPhone 6 - iOS iOS 12.4.9 (November 5, 2020)

please, don't blame me for not fresh but still not so old iOS device
(from my point of view they're full working both for personal and business tasks)

I don't see nothing on both using safari (white page with no error or something else)
changing browser doesn't help (chrome, firefox, edge latest version downloaded by the app store nov-2020)

How can I investigate deeply wtha's happening ?
 - how can I get the safari version (UI-Agent...) from iOS ?
 - how can I debug on the safari/chrome/firefox ? No Web Developer or  Web Developer Tools (with desktop ctrl-alt-i)
 - how can i catch the edumeet server/release which I'm trying to connect to ? 
 - I'm using also https://letsmeet.no to test

**Comment by misi** [comment]
Can you please check your browser developer console logs and send it to us. And also please add in developer console in storage=> localstorage a new variable with a value, so: `debug`:`*`

**Comment by mackostr** [comment]
I've heard of a similar problem with the iPhone (white page) and I did some tests with my iPad Air 2.
A few comments below, but I'm not an advanced iOS user.

1. My tests with https://letsmeet.no:
 - iPad Air 2, iPadOS 13.6, Safari 13 -> works fine

after software update, on the same device:
 - iPad Air 2, iPadOS 14.2 (18B92), Safari 14 -> also works fine

So probably the issue is related to specific combination of device and iOS version.

2. As fas as i know, Safari is an integrated part of the iOS/iPadOS operating system and its version is the same as the current version of iOS that you have.
Some details you can check with online services e.g.:
https://www.whatismybrowser.com/
https://spiderip.com/

3. Debugging webpages on iPads (probably also on iPhone) is not that simple, you can Enable Web Inspector in Safari on iPad but you need regular Mac machine to debug.
Some tips are here: 
https://appletoolbox.com/use-web-inspector-debug-mobile-safari/
https://www.browserstack.com/guide/how-to-debug-on-iphone
    
4. Version number is available in Top bar menu -> More Actions -> About, but you have to be connected first (e.g. from another device).

**Comment by La-Fleur** [comment]
Hi, I can confirm that the issue is related to old Apple device with iOS 12.4.x (tested with other friend's iOS device).
I'm trying to debug safari web pages but without a Mac, it's not easy ...
(I'm trying to use Win10 Chrome to remotely debug Safari but I'm a newbie)

Someone also wrote here on github about the same problem but no further has been made since that
