### ISSUE TITLE
Config option

### ISSUE THREAD

**Issue by Astagor** [havfo/multiparty-meeting#140]
Hi,
could you explain in detail how these 3 parameters influence the connection? Are these per client or per room or per server? Especially the maxIncomingBitrate.
```
                        initialAvailableOutgoingBitrate : 1000000,
                        minimumAvailableOutgoingBitrate : 600000,
                        // Additional options that are not part of WebRtcTransportOptions.
                        maxIncomingBitrate              : 2000000
```

**Comment by havfo** [comment]
`initialAvailableOutgoingBitrate` is the initial bandwidth estimation for a receiver that the server assumes. This means that the server will start sending at this bandwidth (assuming the transport to the client has a bandwidth at least this high because of video-streams) to the client.

`minimumAvailableOutgoingBitrate` is actually deprecated, and will be removed.

`maxIncomingBitrate` is the maximum bandwidth a client is allowed to send to the server in total. This means for example that if this value is lower, you will never be able to send high resolution from the client.

**Comment by havfo** [comment]
It's worth noting that if you have simulcast enabled you will not be able to have as high resolution sent from the client because all layers of the simulcast video must fit inside `maxIncomingBitrate`.

**Comment by Astagor** [comment]
Thank you very much. How do I set simulcast to be enabled or disabled?

**Comment by havfo** [comment]
I have just committed d64247d12dfd458e79046631e94a89b979b496ea that exposes this setting to the client config.

**Comment by Astagor** [comment]
I have tested it. Works great! Thank you very much. My users reported that when using simulcast the overall QoE is much worse, as very often the video gets reduced to lowest resolution and stays like this for a longer time. The prefer to have not so smooth picture and some jumps when the network is bad, but higher resolution.
