### ISSUE TITLE
Is this scenario possible?

### ISSUE THREAD

**Issue by SohelSk** [havfo/multiparty-meeting#448]
Hi, 

I just wanted to know if such a setup would be possible and what would be the typical server required for it?

There is one teacher who will be teaching 100 students at one time and needs to see them all. The audio is optional. 

All 100 will receive both audio and video of that teacher only. No other video/audio stream to be received by them.

Thanks for any help!

**Comment by havfo** [comment]
So, first of all, we have no support for making this use case happen automatically, though it is actually something we are working on. We are fairly close to be able to handle it. Would the teacher need to see all 100 students at the same time?

Soon we will have the feature for the moderator to lock a participant to the spotlight for all participants. This will make the teacher able to lock all students views to the teacher.

Soon we will have the necessary userroles to restrict what type of media a participant is allowed to share (audio/video, we allready have the screen sharing permission). This will make you able to restrict students to only sending video.

Because of the locked spotlight, no student would then be able to see any other student, and because of restricted permissions, no student will be able to broadcast audio to any other student.

That said, from a server perspective, one such room would fit within 1 core (modernish CPU) if you have configured things like the example config.

**Comment by SohelSk** [comment]
Thank you for your reply. 

The teacher wants to keep an eye on all the students. So that would be great.

Looking forward to the new updates.
