### ISSUE TITLE
support toggle camera when using mobile

### ISSUE THREAD

**Issue by quickstreamingmedia** [havfo/multiparty-meeting#70]
support toggle camera when using mobile and support safari as well

**Comment by havfo** [comment]
Camera toggle is supported when using mobile, both enable/disable and changing camera. What is the problem? Safari is supported...sort of. Safari does not support VP8 yet, and because of that is a little hard to it work for all browsers at the same time. If you want to make video work in Safari, change the settings on the server to enable H264 support.
