### ISSUE TITLE
Can't install screen sharing extension

### ISSUE THREAD

**Issue by gytisc** [havfo/multiparty-meeting#77]
Screen sharing extension seems to be missing in Chrome Webstore :(

**Comment by havfo** [comment]
It seems to be available here: https://chrome.google.com/webstore/detail/multiparty-meeting-screen/fckajcjdaabdgnbdcmhhebdglogjfodi

Is this a problem from letsmeet.no, or your own installation?

**Comment by havfo** [comment]
Starting from version 72, chrome no longer requires an extension. This is now handled in multiparty-meeting.

**Comment by gytisc** [comment]
@havfo is it already included in the latest github code?  we see screensharing is disabled in libraries, in me.js   cansharescreen is set to false

**Comment by havfo** [comment]
@gytisc yes, this is in the latest develop branch since: eb81be0ac1318dcdf6d610c5498e8651b710ab63

The relevant code is [here](https://github.com/havfo/multiparty-meeting/blob/develop/app/lib/ScreenShare.js#L317).

This uses the new getDisplayMedia API for Chrome 72+. For Chrome <72 you still need the extension.
